### ISSUE TITLE
De-register runner: must not run with sudo

### ISSUE THREAD

**Issue by sswastioyono18** [macunha1/ansible-github-actions-runner#8]
Hi, thanks for this runner. I was able to create and register the runner but when I want to uninstall it, it says "must not run with sudo"

which config should I change so this step wont return error?
this is what I put into my yml
```
- hosts: all
  roles:
    - role: roles/macunha1.github_actions_runner
      vars:
        gh_runner_config_labels:
          - linux
          - self-hosted
        gh_runner_remove_host: true
        gh_runner_allow_runasroot: "0"
        gh_runner_config_url: some_repo
        gh_runner_config_token: some_token
```

**Comment by macunha1** [comment]
Hi! Thanks for using it and sharing your feedback (:

I suspect that is happening at

```yaml
- name: GitHub Actions Runner [!!] DESTROY! | De-register Runner
  ansible.builtin.command:
    cmd: |-
      {{ gh_runner_path }}/config.sh remove \
        --token "{{ gh_runner_config_token }}"
    chdir: "{{ gh_runner_path }}"
  changed_when: gh_runner_remove_host
```

Ref: https://github.com/macunha1/ansible-github-actions-runner/blob/master/includes/uninstall.yaml#L9-L15

that would be caused by you running the playbook directly with root, if you have any other user available on the host you could try:

```yaml
- hosts: all
  become: true
  become_user: foo
# [...]
```

Otherwise, I think it would be nice to add support for the env `RUNNER_ALLOW_RUNASROOT` similar to https://github.com/macunha1/ansible-github-actions-runner/blob/17b3a07/includes/install.yaml#L61-L65

Ref: https://github.com/actions/runner/blob/3ec20e9/src/Misc/layoutroot/config.sh#L6-L9
