### ISSUE TITLE
Cannot register multiple runners for the same org.

### ISSUE THREAD

**Issue by nagarutu** [macunha1/ansible-github-actions-runner#9]
I was trying to create multiple github runnner for an Org, using indididual repo keys,

```yaml
- name: Install Runner1 on github-runners-ubuntu
  hosts: github-runners-ubuntu

  roles:
    - role: ansible-github-actions-runner
      vars:
        gh_runner_config_labels:
          - ubuntu22
          - linux
          - self-hosted
        gh_runner_config_url: https://github.com/acme.net
        gh_runner_config_token: APERFECTLYFINETOKEN
        gh_runner_config_name: ubuntu-runner1
        gh_runner_allow_runasroot: "Refuse"

    - role: ansible-github-actions-runner
      vars:
        gh_runner_config_labels:
          - ubuntu22
          - linux
          - self-hosted
        gh_runner_config_url: https://github.com/acme.net
        gh_runner_config_token: ANOTHERPERFECTLYFINETOKEN
        gh_runner_config_name: ubuntu-runner2
        gh_runner_allow_runasroot: "Refuse"
```

I expected this to create two runners for on the host and that they both would be online.
Instead it replaced the first runner with the second one.
![image](https://github.com/macunha1/ansible-github-actions-runner/assets/28541236/48581d85-6a9f-4a72-8a7c-b7eceab19b1d)

Ive been looking at the code to understand why its replacing the existing one instead of generating a separate one, but Im not able to figure it out as of yet so figured Id put in an Issue.
